---
title: 汇先知博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: 汇先知博客
  email: kefu@fxianzhi.com
  QQ: http://wpa.qq.com/msgrd?v=3&uin=&site=8259577&menu=yes
  wechat: fxxianzhi
  link: https://blog.fxianzhi.com/
description: 想做产品，却误入程序世界爱上设计的摄影师。
url: https://blog.fxianzhi.com/
repo: https://blog.fxianzhi.com/
rss: "/pages/atom.xml"
gavatar: https://blog.fxianzhi.com/public/img/gavatar.jpg
favicon: https://blog.fxianzhi.com/public/img/favicon.ico
ga:
  id: UA-74789926-1
  url: https://blog.fxianzhi.com/
disqus:
  shortname: gotoshare
active: 每日策略
cates:
- 每日策略
- 每周展望
locals:
  ideas: 汇先知官网
  school: 汇先知学院
  about: 关于我们
  newest: 最新文章
  archive: 全部文章
  search: 黄金盒子
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
- jekyll-mermaid
exclude:
- ".idea/"
- ".github/"
- ".travis/"
- node_modules/
- themes/
- _posts/每周展望/assets
