---
title: 汇先知的博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: 汇先知
  link: http://blog.fxianzhi.com
description: 想做产品，却误入程序世界爱上设计的摄影师。
url: http://blog.fxianzhi.com
repo: http://blog.fxianzhi.com
rss: "/pages/atom.xml"
gavatar: http://blog.fxianzhi.com/public/img/gavatar.jpg
favicon: http://blog.fxianzhi.com/public/img/favicon.ico
ga:
  id: UA-74789926-1
  url: http://blog.fxianzhi.com
disqus:
  shortname: gotoshare
active: 每日策略
cates:
- 每日策略
- 每周展望
locals:
  ideas: 想法
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
- jekyll-mermaid
exclude:
- ".idea/"
- ".github/"
- ".travis/"
- node_modules/
- themes/
- _posts/每周展望/assets
