---
title: 汇先知的博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: 汇先知
  email: kefu@fxianzhi.com
  link: http://blog.fxianzhi.com
  weibo: https://weibo.com/liqing215
  github: https://github.com/JimmyLv
  zhihu: https://www.zhihu.com/people/JimmyLv
  juejin: https://juejin.im/user/5628752900b07a1836200154
  stackoverflow: https://stackoverflow.com/users/5871340/jimmylv
description: 一个梦想着能改变世界的博客。
url: http://blog.fxianzhi.com
repo: https://github.com/JimmyLv/jimmylv.github.io
rss: "/pages/atom.xml"
gavatar: http://blog.fxianzhi.com/public/img/gavatar.jpg
favicon: http://blog.fxianzhi.com/public/img/favicon.ico
ga:
  id: UA-74789926-1
  url: http://blog.fxianzhi.com
disqus:
  shortname: gotoshare
active: 前端
cates:
- 每日策略
- 每周展望
locals:
  ideas: 想法
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
exclude:
- ".idea/"
- ".github/"
- ".travis/"
- node_modules/
- themes/
- _posts/演讲/assets
